#include "stage.h"

#include <stddef.h>

static const AttackPatternDef g_patterns[] = {
    {
        .id = ATTACK_PATTERN_SWEEP_FAN_RING,
        .primary = {.type = ATTACK_EMITTER_FAN,
                    .bullet_kind = BULLET_RING,
                    .speed = 235.0f,
                    .count = 5,
                    .spread_or_width = 1.0f,
                    .radius = 7.0f},
        .cooldown = 1.15f,
    },
    {
        .id = ATTACK_PATTERN_AIMER_FAN_AIMED,
        .primary = {.type = ATTACK_EMITTER_FAN,
                    .bullet_kind = BULLET_AIMED,
                    .speed = 275.0f,
                    .count = 4,
                    .spread_or_width = 0.72f,
                    .radius = 6.5f},
        .cooldown = 1.0f,
    },
    {
        .id = ATTACK_PATTERN_ORBITER_RING_WALL,
        .primary = {.type = ATTACK_EMITTER_RING,
                    .bullet_kind = BULLET_WALL,
                    .speed = 180.0f,
                    .count = 12,
                    .angle_scale = 0.8f,
                    .radius = 7.5f},
        .cooldown = 1.05f,
    },
    {
        .id = ATTACK_PATTERN_SENTINEL_LASER,
        .primary = {.type = ATTACK_EMITTER_VERTICAL_LASER,
                    .count = 1,
                    .radius = 10.0f,
                    .charge_time = 1.0f,
                    .active_time = 0.75f},
        .cooldown = 2.35f,
    },
    {
        .id = ATTACK_PATTERN_BOSS_PHASE_ONE,
        .primary = {.type = ATTACK_EMITTER_RING,
                    .bullet_kind = BULLET_RING,
                    .speed = 185.0f,
                    .count = 18,
                    .angle_scale = 0.6f,
                    .radius = 7.0f},
        .cooldown = 0.72f,
        .secondary = {.type = ATTACK_EMITTER_RING,
                      .bullet_kind = BULLET_AIMED,
                      .speed = 270.0f,
                      .count = 9,
                      .angle_scale = -0.85f,
                      .radius = 5.5f},
    },
    {
        .id = ATTACK_PATTERN_BOSS_PHASE_TWO,
        .primary = {.type = ATTACK_EMITTER_FAN,
                    .bullet_kind = BULLET_AIMED,
                    .speed = 310.0f,
                    .count = 9,
                    .spread_or_width = 1.35f,
                    .radius = 6.0f},
        .cooldown = 0.56f,
        .secondary = {.type = ATTACK_EMITTER_CURTAIN,
                      .bullet_kind = BULLET_WALL,
                      .speed = 220.0f,
                      .count = 10,
                      .spread_or_width = 476.0f,
                      .radius = 8.5f},
        .secondary_cooldown = 1.6f,
        .secondary_uses_aux_timer = true,
    },
    {
        .id = ATTACK_PATTERN_BOSS_PHASE_THREE,
        .primary = {.type = ATTACK_EMITTER_SPIRAL_BURST,
                    .bullet_kind = BULLET_SPIRAL,
                    .speed = 240.0f,
                    .count = 4,
                    .angle_scale = 3.8f,
                    .radius = 6.5f},
        .cooldown = 0.09f,
        .secondary = {.type = ATTACK_EMITTER_FAN,
                      .bullet_kind = BULLET_WALL,
                      .speed = 340.0f,
                      .count = 11,
                      .spread_or_width = 1.7f,
                      .radius = 7.0f},
        .secondary_cooldown = 1.05f,
        .secondary_uses_aux_timer = true,
    },
    {
        .id = ATTACK_PATTERN_ARRAY_BOSS_PHASE_ONE,
        .primary = {.type = ATTACK_EMITTER_FAN,
                    .bullet_kind = BULLET_AIMED,
                    .speed = 260.0f,
                    .count = 6,
                    .spread_or_width = 0.92f,
                    .radius = 6.0f},
        .cooldown = 0.74f,
        .secondary = {.type = ATTACK_EMITTER_VERTICAL_LASER,
                      .count = 2,
                      .spread_or_width = 190.0f,
                      .radius = 11.0f,
                      .charge_time = 1.1f,
                      .active_time = 0.8f},
        .secondary_cooldown = 1.95f,
        .secondary_uses_aux_timer = true,
    },
    {
        .id = ATTACK_PATTERN_ARRAY_BOSS_PHASE_TWO,
        .primary = {.type = ATTACK_EMITTER_RING,
                    .bullet_kind = BULLET_WALL,
                    .speed = 190.0f,
                    .count = 14,
                    .angle_scale = 0.58f,
                    .radius = 7.5f},
        .cooldown = 0.9f,
        .secondary = {.type = ATTACK_EMITTER_VERTICAL_LASER,
                      .count = 3,
                      .spread_or_width = 250.0f,
                      .radius = 12.0f,
                      .charge_time = 0.95f,
                      .active_time = 0.95f},
        .secondary_cooldown = 1.75f,
        .secondary_uses_aux_timer = true,
    },
    {
        .id = ATTACK_PATTERN_ARRAY_BOSS_PHASE_THREE,
        .primary = {.type = ATTACK_EMITTER_SPIRAL_BURST,
                    .bullet_kind = BULLET_SPIRAL,
                    .speed = 255.0f,
                    .count = 5,
                    .angle_scale = 3.2f,
                    .radius = 6.5f},
        .cooldown = 0.11f,
        .secondary = {.type = ATTACK_EMITTER_VERTICAL_LASER,
                      .count = 1,
                      .radius = 20.0f,
                      .charge_time = 0.78f,
                      .active_time = 1.3f},
        .secondary_cooldown = 1.45f,
        .secondary_uses_aux_timer = true,
    },
};

static const EnemyArchetypeDef g_archetypes[] = {
    {
        .id = ENEMY_ARCHETYPE_SWEEP,
        .kind = ENEMY_SWEEP,
        .movement = ENEMY_MOVE_SWEEP_BOUNCE,
        .radius = 18.0f,
        .hp = 16,
        .base_cooldown = 0.65f,
        .collision_scale = 0.55f,
        .reward = 100,
        .lifetime = 8.0f,
        .attack_start_y = 30.0f,
        .move_param_a = 26.0f,
        .phase_patterns = {ATTACK_PATTERN_SWEEP_FAN_RING, ATTACK_PATTERN_NONE, ATTACK_PATTERN_NONE},
    },
    {
        .id = ENEMY_ARCHETYPE_AIMER,
        .kind = ENEMY_AIMER,
        .movement = ENEMY_MOVE_AIMER_DRIFT,
        .radius = 20.0f,
        .hp = 26,
        .base_cooldown = 1.0f,
        .collision_scale = 0.55f,
        .reward = 180,
        .lifetime = 7.0f,
        .attack_start_y = 40.0f,
        .move_param_a = 28.0f,
        .move_param_b = 80.0f,
        .phase_patterns = {ATTACK_PATTERN_AIMER_FAN_AIMED, ATTACK_PATTERN_NONE,
                           ATTACK_PATTERN_NONE},
    },
    {
        .id = ENEMY_ARCHETYPE_AIMER_HEAVY,
        .kind = ENEMY_AIMER,
        .movement = ENEMY_MOVE_AIMER_DRIFT,
        .radius = 20.0f,
        .hp = 34,
        .base_cooldown = 1.0f,
        .collision_scale = 0.55f,
        .reward = 220,
        .lifetime = 7.0f,
        .attack_start_y = 40.0f,
        .move_param_a = 28.0f,
        .move_param_b = 80.0f,
        .phase_patterns = {ATTACK_PATTERN_AIMER_FAN_AIMED, ATTACK_PATTERN_NONE,
                           ATTACK_PATTERN_NONE},
    },
    {
        .id = ENEMY_ARCHETYPE_ORBITER,
        .kind = ENEMY_ORBITER,
        .movement = ENEMY_MOVE_ORBIT_SINE,
        .radius = 22.0f,
        .hp = 32,
        .base_cooldown = 0.75f,
        .collision_scale = 0.55f,
        .reward = 240,
        .lifetime = 7.8f,
        .attack_start_y = 45.0f,
        .move_param_a = 86.0f,
        .move_param_b = 1.9f,
        .phase_patterns = {ATTACK_PATTERN_ORBITER_RING_WALL, ATTACK_PATTERN_NONE,
                           ATTACK_PATTERN_NONE},
    },
    {
        .id = ENEMY_ARCHETYPE_SENTINEL,
        .kind = ENEMY_SENTINEL,
        .movement = ENEMY_MOVE_SENTINEL_HOLD,
        .radius = 24.0f,
        .hp = 34,
        .base_cooldown = 1.2f,
        .collision_scale = 0.58f,
        .reward = 260,
        .lifetime = 9.2f,
        .attack_start_y = 60.0f,
        .move_param_a = 150.0f,
        .move_param_b = 180.0f,
        .phase_patterns = {ATTACK_PATTERN_SENTINEL_LASER, ATTACK_PATTERN_NONE, ATTACK_PATTERN_NONE},
    },
    {
        .id = ENEMY_ARCHETYPE_BOSS_CORE,
        .kind = ENEMY_BOSS,
        .movement = ENEMY_MOVE_BOSS_CORE,
        .radius = 46.0f,
        .hp = 320,
        .base_cooldown = 0.6f,
        .base_aux_cooldown = 1.25f,
        .reward = 3000,
        .attack_start_y = 30.0f,
        .move_param_a = 165.0f,
        .move_param_b = 158.0f,
        .move_param_c = 0.72f,
        .phase_patterns = {ATTACK_PATTERN_BOSS_PHASE_ONE, ATTACK_PATTERN_BOSS_PHASE_TWO,
                           ATTACK_PATTERN_BOSS_PHASE_THREE},
        .phase_ratios = {0.6875f, 0.375f},
    },
    {
        .id = ENEMY_ARCHETYPE_ARRAY_BOSS,
        .kind = ENEMY_BOSS,
        .movement = ENEMY_MOVE_BOSS_CORE,
        .radius = 50.0f,
        .hp = 380,
        .base_cooldown = 0.75f,
        .base_aux_cooldown = 1.2f,
        .reward = 4200,
        .attack_start_y = 32.0f,
        .move_param_a = 158.0f,
        .move_param_b = 188.0f,
        .move_param_c = 0.58f,
        .phase_patterns = {ATTACK_PATTERN_ARRAY_BOSS_PHASE_ONE, ATTACK_PATTERN_ARRAY_BOSS_PHASE_TWO,
                           ATTACK_PATTERN_ARRAY_BOSS_PHASE_THREE},
        .phase_ratios = {0.68f, 0.34f},
    },
};

static const WaveDef g_waves[] = {
    {
        .id = WAVE_OPEN_SWEEP_ROW,
        .spawn_count = 5,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.089286f,
                 .y_offset = -20.0f,
                 .velocity_x = 50.0f,
                 .velocity_y = 82.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.294643f,
                 .y_offset = -20.0f,
                 .velocity_x = -50.0f,
                 .velocity_y = 82.0f,
                 .cooldown_offset = 0.08f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.500000f,
                 .y_offset = -20.0f,
                 .velocity_x = 50.0f,
                 .velocity_y = 82.0f,
                 .cooldown_offset = 0.16f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.705357f,
                 .y_offset = -20.0f,
                 .velocity_x = -50.0f,
                 .velocity_y = 82.0f,
                 .cooldown_offset = 0.24f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.910714f,
                 .y_offset = -20.0f,
                 .velocity_x = 50.0f,
                 .velocity_y = 82.0f,
                 .cooldown_offset = 0.32f},
            },
    },
    {
        .id = WAVE_AIMER_PAIR,
        .spawn_count = 2,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.214286f,
                 .y_offset = -10.0f,
                 .velocity_x = 42.0f,
                 .velocity_y = 52.0f},
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.785714f,
                 .y_offset = -40.0f,
                 .velocity_x = -42.0f,
                 .velocity_y = 52.0f,
                 .cooldown_offset = 0.2f},
            },
    },
    {
        .id = WAVE_ORBIT_PAIR,
        .spawn_count = 2,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.267857f,
                 .y_offset = -40.0f,
                 .velocity_y = 42.0f},
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.732143f,
                 .y_offset = -85.0f,
                 .velocity_y = 42.0f,
                 .cooldown_offset = 0.35f,
                 .movement_phase_offset = 1.1f},
            },
    },
    {
        .id = WAVE_MID_SWEEP_PRESSURE,
        .spawn_count = 7,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.089286f,
                 .y_offset = -30.0f,
                 .velocity_x = 90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.253571f,
                 .y_offset = -30.0f,
                 .velocity_x = -90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.08f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.417857f,
                 .y_offset = -30.0f,
                 .velocity_x = 90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.16f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.582143f,
                 .y_offset = -30.0f,
                 .velocity_x = -90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.24f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.746429f,
                 .y_offset = -30.0f,
                 .velocity_x = 90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.32f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.910714f,
                 .y_offset = -30.0f,
                 .velocity_x = -90.0f,
                 .velocity_y = 105.0f,
                 .cooldown_offset = 0.40f},
                {.archetype = ENEMY_ARCHETYPE_AIMER_HEAVY,
                 .x_factor = 0.500000f,
                 .y_offset = -60.0f,
                 .velocity_y = 64.0f},
            },
    },
    {
        .id = WAVE_LATE_PINCH,
        .spawn_count = 6,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.214286f,
                 .y_offset = -20.0f,
                 .velocity_x = 58.0f,
                 .velocity_y = 52.0f},
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.785714f,
                 .y_offset = -50.0f,
                 .velocity_x = -58.0f,
                 .velocity_y = 52.0f,
                 .cooldown_offset = 0.2f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.089286f,
                 .y_offset = -20.0f,
                 .velocity_x = 50.0f,
                 .velocity_y = 128.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.363095f,
                 .y_offset = -20.0f,
                 .velocity_x = -50.0f,
                 .velocity_y = 128.0f,
                 .cooldown_offset = 0.08f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.636905f,
                 .y_offset = -20.0f,
                 .velocity_x = 50.0f,
                 .velocity_y = 128.0f,
                 .cooldown_offset = 0.16f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.910714f,
                 .y_offset = -20.0f,
                 .velocity_x = -50.0f,
                 .velocity_y = 128.0f,
                 .cooldown_offset = 0.24f},
            },
    },
    {
        .id = WAVE_BOSS_ENTRY,
        .clear_non_boss_on_start = true,
        .spawn_count = 1,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_BOSS_CORE,
                 .x_factor = 0.500000f,
                 .y_offset = -120.0f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_OPEN_CROSS,
        .spawn_count = 6,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.125000f,
                 .y_offset = -18.0f,
                 .velocity_x = 65.0f,
                 .velocity_y = 92.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.335000f,
                 .y_offset = -40.0f,
                 .velocity_x = -65.0f,
                 .velocity_y = 92.0f,
                 .cooldown_offset = 0.08f},
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.500000f,
                 .y_offset = -78.0f,
                 .velocity_y = 62.0f,
                 .cooldown_offset = 0.20f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.665000f,
                 .y_offset = -40.0f,
                 .velocity_x = 65.0f,
                 .velocity_y = 92.0f,
                 .cooldown_offset = 0.16f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.875000f,
                 .y_offset = -18.0f,
                 .velocity_x = -65.0f,
                 .velocity_y = 92.0f,
                 .cooldown_offset = 0.24f},
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.500000f,
                 .y_offset = -140.0f,
                 .velocity_y = 48.0f,
                 .movement_phase_offset = 0.8f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_SENTINEL_PAIR,
        .spawn_count = 2,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.250000f,
                 .y_offset = -50.0f,
                 .velocity_y = 120.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.750000f,
                 .y_offset = -92.0f,
                 .velocity_y = 120.0f,
                 .cooldown_offset = 0.55f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_SWEEP_LATTICE,
        .spawn_count = 7,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.100000f,
                 .y_offset = -24.0f,
                 .velocity_x = 96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.240000f,
                 .y_offset = -42.0f,
                 .velocity_x = -96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.08f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.380000f,
                 .y_offset = -60.0f,
                 .velocity_x = 96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.16f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.620000f,
                 .y_offset = -60.0f,
                 .velocity_x = -96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.24f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.760000f,
                 .y_offset = -42.0f,
                 .velocity_x = 96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.32f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.900000f,
                 .y_offset = -24.0f,
                 .velocity_x = -96.0f,
                 .velocity_y = 112.0f,
                 .cooldown_offset = 0.40f},
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.500000f,
                 .y_offset = -122.0f,
                 .velocity_y = 52.0f,
                 .cooldown_offset = 0.35f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_SENTINEL_WALL,
        .spawn_count = 3,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.180000f,
                 .y_offset = -40.0f,
                 .velocity_y = 126.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.500000f,
                 .y_offset = -78.0f,
                 .velocity_y = 126.0f,
                 .cooldown_offset = 0.55f},
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.820000f,
                 .y_offset = -116.0f,
                 .velocity_y = 126.0f,
                 .cooldown_offset = 1.10f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_ORBIT_BREAK,
        .spawn_count = 5,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.220000f,
                 .y_offset = -50.0f,
                 .velocity_y = 48.0f,
                 .movement_phase_offset = 0.2f},
                {.archetype = ENEMY_ARCHETYPE_ORBITER,
                 .x_factor = 0.780000f,
                 .y_offset = -90.0f,
                 .velocity_y = 48.0f,
                 .cooldown_offset = 0.30f,
                 .movement_phase_offset = 1.4f},
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.180000f,
                 .y_offset = -20.0f,
                 .velocity_x = 62.0f,
                 .velocity_y = 58.0f},
                {.archetype = ENEMY_ARCHETYPE_AIMER,
                 .x_factor = 0.820000f,
                 .y_offset = -54.0f,
                 .velocity_x = -62.0f,
                 .velocity_y = 58.0f,
                 .cooldown_offset = 0.18f},
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.500000f,
                 .y_offset = -132.0f,
                 .velocity_y = 120.0f,
                 .cooldown_offset = 0.55f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_FINAL_PRESSURE,
        .spawn_count = 7,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.280000f,
                 .y_offset = -42.0f,
                 .velocity_y = 132.0f,
                 .cooldown_offset = 0.00f},
                {.archetype = ENEMY_ARCHETYPE_SENTINEL,
                 .x_factor = 0.720000f,
                 .y_offset = -84.0f,
                 .velocity_y = 132.0f,
                 .cooldown_offset = 0.65f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.100000f,
                 .y_offset = -18.0f,
                 .velocity_x = 70.0f,
                 .velocity_y = 136.0f,
                 .cooldown_offset = 0.10f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.330000f,
                 .y_offset = -28.0f,
                 .velocity_x = -70.0f,
                 .velocity_y = 136.0f,
                 .cooldown_offset = 0.18f},
                {.archetype = ENEMY_ARCHETYPE_AIMER_HEAVY,
                 .x_factor = 0.500000f,
                 .y_offset = -140.0f,
                 .velocity_y = 72.0f,
                 .cooldown_offset = 0.35f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.670000f,
                 .y_offset = -28.0f,
                 .velocity_x = 70.0f,
                 .velocity_y = 136.0f,
                 .cooldown_offset = 0.26f},
                {.archetype = ENEMY_ARCHETYPE_SWEEP,
                 .x_factor = 0.900000f,
                 .y_offset = -18.0f,
                 .velocity_x = -70.0f,
                 .velocity_y = 136.0f,
                 .cooldown_offset = 0.34f},
            },
    },
    {
        .id = WAVE_STAGE_TWO_BOSS_ENTRY,
        .clear_non_boss_on_start = true,
        .spawn_count = 1,
        .spawns =
            {
                {.archetype = ENEMY_ARCHETYPE_ARRAY_BOSS,
                 .x_factor = 0.500000f,
                 .y_offset = -128.0f},
            },
    },
};

static const StageCue g_stage_one_cues[] = {
    {.trigger_time = 0.8f, .wave = WAVE_OPEN_SWEEP_ROW},
    {.trigger_time = 4.6f, .wave = WAVE_AIMER_PAIR},
    {.trigger_time = 8.2f, .wave = WAVE_ORBIT_PAIR},
    {.trigger_time = 12.4f, .wave = WAVE_MID_SWEEP_PRESSURE},
    {.trigger_time = 17.0f, .wave = WAVE_LATE_PINCH},
    {.trigger_time = 22.0f, .wave = WAVE_BOSS_ENTRY},
};

static const StageCue g_stage_two_cues[] = {
    {.trigger_time = 0.8f, .wave = WAVE_STAGE_TWO_OPEN_CROSS},
    {.trigger_time = 4.3f, .wave = WAVE_STAGE_TWO_SENTINEL_PAIR},
    {.trigger_time = 8.4f, .wave = WAVE_STAGE_TWO_SWEEP_LATTICE},
    {.trigger_time = 12.6f, .wave = WAVE_STAGE_TWO_SENTINEL_WALL},
    {.trigger_time = 17.0f, .wave = WAVE_STAGE_TWO_ORBIT_BREAK},
    {.trigger_time = 21.1f, .wave = WAVE_STAGE_TWO_FINAL_PRESSURE},
    {.trigger_time = 25.8f, .wave = WAVE_STAGE_TWO_BOSS_ENTRY},
};

static const StageDef g_stages[] = {
    {
        .id = STAGE_ONE,
        .next_stage = STAGE_TWO,
        .name = "stage-one",
        .hud_label = "ONE",
        .boss_wave = WAVE_BOSS_ENTRY,
        .cue_count = (int)(sizeof(g_stage_one_cues) / sizeof(g_stage_one_cues[0])),
        .cues = g_stage_one_cues,
    },
    {
        .id = STAGE_TWO,
        .next_stage = STAGE_NONE,
        .name = "stage-two",
        .hud_label = "TWO",
        .boss_wave = WAVE_STAGE_TWO_BOSS_ENTRY,
        .cue_count = (int)(sizeof(g_stage_two_cues) / sizeof(g_stage_two_cues[0])),
        .cues = g_stage_two_cues,
    },
};

const StageDef *StageGetDefault(void) { return &g_stages[0]; }

const StageDef *StageGetById(StageId id)
{
    for (int i = 0; i < (int)(sizeof(g_stages) / sizeof(g_stages[0])); ++i)
    {
        if (g_stages[i].id == id)
        {
            return &g_stages[i];
        }
    }

    return NULL;
}

const StageDef *StageGetNext(const StageDef *stage)
{
    if (stage == NULL || stage->next_stage == STAGE_NONE)
    {
        return NULL;
    }

    return StageGetById(stage->next_stage);
}

const WaveDef *StageGetWaveDefinition(WaveId id)
{
    for (int i = 0; i < (int)(sizeof(g_waves) / sizeof(g_waves[0])); ++i)
    {
        if (g_waves[i].id == id)
        {
            return &g_waves[i];
        }
    }

    return NULL;
}

const EnemyArchetypeDef *StageGetEnemyArchetype(EnemyArchetypeId id)
{
    for (int i = 0; i < (int)(sizeof(g_archetypes) / sizeof(g_archetypes[0])); ++i)
    {
        if (g_archetypes[i].id == id)
        {
            return &g_archetypes[i];
        }
    }

    return NULL;
}

const AttackPatternDef *StageGetAttackPattern(AttackPatternId id)
{
    for (int i = 0; i < (int)(sizeof(g_patterns) / sizeof(g_patterns[0])); ++i)
    {
        if (g_patterns[i].id == id)
        {
            return &g_patterns[i];
        }
    }

    return NULL;
}
